[features]
seeds = false
[programs.localnet]
solkitties = "Bb73evuaitYgZNXotqaF2UsNZsoLaAyGmdNwYR4Wmg6X"
[programs.devnet]
solkitties = "Bb73evuaitYgZNXotqaF2UsNZsoLaAyGmdNwYR4Wmg6X"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/john/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
